# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a413285599e374d97d71fcf5cef2fe6b642e02653fbeab14abe5a1ebe53cb2c52c3d19f6c719c29e9aacfd82e02eea5de290c03d8e471288c0c73a4add4dc720

test:
  secret_key_base: f282e49f3368ac3de8e3bb75176eecd764cc4276926020b0b6411fac4c294396bd69b64535848c8e5c113ac19f8b92ea55d860065840bca5f20f5bff48d8493f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
